version: "3.9"

services:
  kiyomi-api:
    restart: unless-stopped
    environment: 
      - PORT=${KIYOMI_API_PORT}
      - HOST=0.0.0.0
      - DB_DIR=${DB_DIR}
    volumes:
      - kiyomi-db:${DB_DIR}
    build:
      context: ./kiyomi-api
    ports:
      - ${KIYOMI_API_PORT}
  mal-api-proxy:
    restart: unless-stopped
    environment: 
      - PORT=${MAL_API_PROXY_PORT}
      - HOST=0.0.0.0
      - NODE_ENV=production
    build: 
      context: ./mal-api-proxy
    ports:
      - ${MAL_API_PROXY_PORT}
  kiyomi:
    restart: unless-stopped
    depends_on:
      - kiyomi-api
      - mal-api-proxy
    build:
      context: ./kiyomi
      dockerfile: Dockerfile.prod
    ports:
      - 80:80

volumes:
  kiyomi-db:
