version: '3'

services:
  db:
    image: kiyomi-mariadb:prod
    restart: always
    build:
      context: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306

  kiyomi-api:
    image: kiyomi-api:0.1.2
    restart: unless-stopped
    environment: 
      - PORT=${API_PORT}
      - MAL_API_CLIENT_ID=${MAL_API_CLIENT_ID}
      - MAL_API_CLIENT_SECRET=${MAL_API_CLIENT_SECRET}
      - MAL_API_REFRESH_TOKEN=${MAL_API_REFRESH_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    build:
      context: ./kiyomi-api
      dockerfile: Dockerfile.prod
    ports:
      - ${API_PORT}
    depends_on:
      - db

  kiyomi:
    image: kiyomi:0.1.2
    environment: 
      - API_PORT=${API_PORT}
    depends_on:
      - kiyomi-api
    build:
      context: ./kiyomi
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443

