version: "3.9"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  kiyomi-api:
    restart: unless-stopped
    environment: 
      - API_PORT=${API_PORT}
      - PROXY_PORT=${PROXY_PORT}
      - HOST=0.0.0.0
      - MAL_API_CLIENT_ID=${MAL_API_CLIENT_ID}
      - MAL_API_CLIENT_SECRET=${MAL_API_CLIENT_SECRET}
      - MAL_API_REFRESH_TOKEN=${MAL_API_REFRESH_TOKEN}
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PW=example
      - DB_DATABASE=kiyomi
    volumes:
      - ./kiyomi-api:/opt/kiyomi/api
    build:
      context: ./kiyomi-api
    ports:
      - ${API_PORT}
    depends_on:
      - db

  kiyomi:
    image: kiyomi-dev
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - PORT=${APP_PORT}
      - API_PORT=${API_PORT}
    volumes:
      - ./kiyomi/:/opt/kiyomi/app
    depends_on:
      - kiyomi-api
    build:
      context: ./kiyomi
    ports:
      - 3000:3000

