version: "3.9"

services:
  kiyomi-api:
    restart: unless-stopped
    environment: 
      - PORT=${KIYOMI_API_PORT}
      - HOST=0.0.0.0
      - DB_DIR=${DB_DIR}
    volumes:
      - kiyomi-db:${DB_DIR}
    build:
      context: ./kiyomi-api
    ports:
      - ${KIYOMI_API_PORT}:${KIYOMI_API_PORT}
  mal-api-proxy:
    restart: unless-stopped
    environment: 
      - PORT=${MAL_API_PROXY_PORT}:${MAL_API_PROXY_PORT}
      - HOST=0.0.0.0
      - NODE_ENV=development
      - MAL_API_CLIENT_ID=${MAL_API_CLIENT_ID}
      - MAL_API_CLIENT_SECRET=${MAL_API_CLIENT_SECRET}
      - MAL_API_REFRESH_TOKEN=${MAL_API_REFRESH_TOKEN}
    build: 
      context: ./mal-api-proxy
    ports:
      - ${MAL_API_PROXY_PORT}
  kiyomi:
    image: kiyomi-dev
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./kiyomi/:/kiyomi/
      - /kiyomi/node_modules/
    depends_on:
      - kiyomi-api
      - mal-api-proxy
    build:
      context: ./kiyomi
    ports:
      - 3000:3000

volumes:
  kiyomi-db:
