version: '3'

services:
  kiyomi-api:
    image: registry.pattern.blue/kiyomi-api:${TAG}
    restart: unless-stopped
    environment: 
      - PORT=${API_PORT}
      - MAL_API_CLIENT_ID=${MAL_API_CLIENT_ID}
      - MAL_API_CLIENT_SECRET=${MAL_API_CLIENT_SECRET}
      - MAL_API_REFRESH_TOKEN=${MAL_API_REFRESH_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - ${API_PORT}

  kiyomi:
    restart: unless-stopped
    image: registry.pattern.blue/kiyomi:${TAG}
    environment: 
      - API_PORT=${API_PORT}
    depends_on:
      - kiyomi-api
    ports:
      - 80:80
      - 443:443

volumes:
  mariadb-data:
