FROM node:14-slim as build
WORKDIR /opt/kiyomi/app
COPY package*.json ./
COPY package.json .
COPY yarn.lock .
RUN yarn install --production
COPY . . 
RUN yarn build

FROM nginx:latest
COPY nginx /etc/nginx/templates
COPY cert/cert.pem /etc/nginx/cert.pem
COPY cert/privkey.pem /etc/nginx/privkey.pem
COPY --from=build /opt/kiyomi/app/build /usr/share/nginx/html
