apiVersion: v1
kind: Service
metadata:
  name: kiyomi-api
  namespace: kiyomi
spec:
  selector:
    app: kiyomi-api
  ports:
  - port: 3001
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiyomi-api 
  namespace: kiyomi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiyomi-api
  template:
    metadata:
      labels:
        app: kiyomi-api 
    spec:
      containers:
      - name: kiyomi-api 
        image: registry.pattern.blue/kiyomi-api
        imagePullPolicy: Always
        env:
        - name: PORT
          value: '3001'
        - name: MAL_API_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mal-credentials
              key: client-id
        - name: MAL_API_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mal-credentials
              key: client-secret
        - name: MAL_API_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: mal-credentials
              key: refresh-token
        - name: DB_HOST
          value: 'kiyomi-db'
        - name: DB_USER
          value: 'kiyomi@%'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kiyomi-mariadb-credentials
              key: user-password
        - name: DB_DATABASE
          value: kiyomi
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"