apiVersion: v1
kind: Service
metadata:
  name: kiyomi-db
  namespace: kiyomi
spec:
  selector:
    app: kiyomi-db 
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiyomi-db
  namespace: kiyomi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiyomi-db
  template:
    metadata:
      labels:
        app: kiyomi-db
    spec:
      containers:
      - name: kiyomi-db
        image: registry.pattern.blue/kiyomi-db
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiyomi-mariadb-credentials
                key: root-password
          - name: MYSQL_DATABASE
            value: kiyomi
          - name: MYSQL_USER
            value: kiyomi@%
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiyomi-mariadb-credentials
                key: user-password
        resources:
          limits:
            memory: "1024Mi" 
            cpu: "250m"
