apiVersion: v1
kind: Service
metadata:
  name: kiyomi-web
  namespace: kiyomi
spec:
  type: NodePort
  selector:
    app: kiyomi-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30111 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiyomi-web 
  namespace: kiyomi
spec:
  selector:
    matchLabels:
      app: kiyomi-web
  template:
    metadata:
      labels:
        app: kiyomi-web
    spec:
      containers:
      - name: kiyomi-web
        image: registry.pattern.blue/kiyomi
        imagePullPolicy: IfNotPresent 
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi" 
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: kiyomi-web-nginx-config
      volumes:
        - name: kiyomi-web-nginx-config
          configMap:
            name: kiyomi-web-nginx-config
            items:
              - key: default.conf
                path: default.conf
        