apiVersion: v1
kind: Service
metadata:
  name: kiyomi-web
  namespace: kiyomi
spec:
  type: NodePort
  externalIPs:
    - "192.168.108.195" 
  selector:
    app: kiyomi-web
  ports:
  - name: kiyomi-http
    port: 8034
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiyomi-web 
  namespace: kiyomi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiyomi-web
  template:
    metadata:
      labels:
        app: kiyomi-web
    spec:
      containers:
      - name: kiyomi-web
        image: registry.pattern.blue/kiyomi
        imagePullPolicy: Always 
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi" 
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: kiyomi-web-nginx-config
      volumes:
        - name: kiyomi-web-nginx-config
          configMap:
            name: kiyomi-web-nginx-config 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiyomi-web-nginx-config
  namespace: kiyomi
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        location / {
            try_files $uri /index.html;
        }

        location /anime/ {
            proxy_pass http://kiyomi-api:3001;
        }

        location /kiyomi/ {
            proxy_pass http://kiyomi-api:3001;
        }
    }

